[platformio]
src_dir = src
test_dir = test
build_dir = build
default_envs = native_test

[env:esp32]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
test_ignore = *
build_flags =
    -D WIFI_SSID=\"\"
    -D WIFI_PASS=\"\"
lib_deps =
    nanopb/Nanopb@0.4.8

extra_scripts =
    pre:scripts/proto_build.py

[env:native_test]
platform = native
test_framework = googletest
build_flags =
    -std=c++17
    -Wall
    -Wextra
lib_deps =
    nanopb/Nanopb@0.4.8

extra_scripts =
    pre:scripts/proto_build.py
