[platformio]
src_dir = src
test_dir = test
build_dir = /tmp/espMeshFlood_build
default_envs = esp32

[env:esp32]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
upload_speed = 921600
monitor_speed = 115200
test_ignore = *
build_flags =
    -std=gnu++14
    -D WIFI_SSID=\"\"
    -D WIFI_PASS=\"\"
lib_deps =
    nanopb/Nanopb@0.4.8

extra_scripts =
    pre:scripts/proto_build.py

[env:native_test]
platform = native
test_framework = googletest
build_flags =
    -std=c++17
    -Wall
    -Wextra
lib_deps =
    nanopb/Nanopb@0.4.8

extra_scripts =
    pre:scripts/proto_build.py
